/*
 * Copyright (C) Huawei Technologies Co., Ltd. 2023. All rights reserved.
 * SPDX-License-Identifier: MIT
 */
#ifndef VATOMIC_UNDEF_H
#define VATOMIC_UNDEF_H

#undef V_ALIGNED2
#undef V_ALIGNED4
#undef V_ALIGNED8
#undef V_ALIGNEDP
#undef V_ALIGNEDSZ
#undef V_AWAIT_B
#undef V_AWAIT_BNOT
#undef V_ASM
#undef V_FENCE_RLX_INSTRUCTION
#undef V_AWAIT_OP
#undef V_BEQ
#undef V_BHS
#undef V_BNE
#undef V_CAS
#undef V_CBNZ
#undef V_CBZ
#undef V_CMP
#undef V_CMPEQ
#undef V_CMPEQ_32
#undef V_CMPEQ_64
#undef V_CMPI
#undef V_CODE_ALIGN
#undef V_DEC
#undef V_DEFINE_add
#undef V_DEFINE_add_get
#undef V_DEFINE_and
#undef V_DEFINE_and_get
#undef V_DEFINE_await
#undef V_DEFINE_await_COND_add
#undef V_DEFINE_await_COND_OP
#undef V_DEFINE_await_COND_set
#undef V_DEFINE_await_COND_sub
#undef V_DEFINE_await_counter
#undef V_DEFINE_await_mask
#undef V_DEFINE_cmpxchg
#undef V_DEFINE_dec
#undef V_DEFINE_dec_get
#undef V_DEFINE_fence
#undef V_DEFINE_FUNC
#undef V_DEFINE_FUNC_1
#undef V_DEFINE_FUNC_2
#undef V_DEFINE_FUNC_3
#undef V_DEFINE_FUNC_4
#undef V_DEFINE_FUNC_5
#undef V_DEFINE_FUNC_6
#undef V_DEFINE_get_add
#undef V_DEFINE_get_and
#undef V_DEFINE_get_dec
#undef V_DEFINE_get_inc
#undef V_DEFINE_get_max
#undef V_DEFINE_get_or
#undef V_DEFINE_get_sub
#undef V_DEFINE_get_xor
#undef V_DEFINE_inc
#undef V_DEFINE_inc_get
#undef V_DEFINE_init
#undef V_DEFINE_max
#undef V_DEFINE_max_get
#undef V_DEFINE_or
#undef V_DEFINE_or_get
#undef V_DEFINE_read
#undef V_DEFINE_sub
#undef V_DEFINE_sub_get
#undef V_DEFINE_write
#undef V_DEFINE_write_32
#undef V_DEFINE_write_64
#undef V_DEFINE_xchg
#undef V_DEFINE_xor
#undef V_DEFINE_xor_get
#undef V_DEFINE_BUILTIN_cmpxchg
#undef V_DEFINE_BUILTIN_fence
#undef V_DEFINE_BUILTIN_get_add
#undef V_DEFINE_BUILTIN_get_and
#undef V_DEFINE_BUILTIN_get_or
#undef V_DEFINE_BUILTIN_get_sub
#undef V_DEFINE_BUILTIN_get_xor
#undef V_DEFINE_BUILTIN_read
#undef V_DEFINE_BUILTIN_write
#undef V_DEFINE_BUILTIN_xchg
#undef V_DEFINE_FALLBACK_add
#undef V_DEFINE_FALLBACK_add_get
#undef V_DEFINE_FALLBACK_and
#undef V_DEFINE_FALLBACK_and_get
#undef V_DEFINE_FALLBACK_await
#undef V_DEFINE_FALLBACK_await_counter
#undef V_DEFINE_FALLBACK_await_mask
#undef V_DEFINE_FALLBACK_dec
#undef V_DEFINE_FALLBACK_dec_get
#undef V_DEFINE_FALLBACK_get_dec
#undef V_DEFINE_FALLBACK_get_inc
#undef V_DEFINE_FALLBACK_get_max
#undef V_DEFINE_FALLBACK_inc
#undef V_DEFINE_FALLBACK_inc_get
#undef V_DEFINE_FALLBACK_init
#undef V_DEFINE_FALLBACK_max
#undef V_DEFINE_FALLBACK_max_get
#undef V_DEFINE_FALLBACK_or
#undef V_DEFINE_FALLBACK_or_get
#undef V_DEFINE_FALLBACK_sub
#undef V_DEFINE_FALLBACK_sub_get
#undef V_DEFINE_FALLBACK_xor
#undef V_DEFINE_FALLBACK_xor_get
#undef V_FENCE
#undef V_FENCE_mo_acq
#undef V_FENCE_mo_rel
#undef V_FENCE_mo_rlx
#undef V_FENCE_mo_seq
#undef V_FENCE_POST_LD
#undef V_FENCE_POST_LD_mo_acq
#undef V_FENCE_POST_LD_mo_rel
#undef V_FENCE_POST_LD_mo_rlx
#undef V_FENCE_POST_LD_mo_seq
#undef V_FENCE_POST_ST
#undef V_FENCE_POST_ST_mo_acq
#undef V_FENCE_POST_ST_mo_rel
#undef V_FENCE_POST_ST_mo_rlx
#undef V_FENCE_POST_ST_mo_seq
#undef V_FENCE_PRE_ST
#undef V_FENCE_PRE_ST_mo_acq
#undef V_FENCE_PRE_ST_mo_rel
#undef V_FENCE_PRE_ST_mo_rlx
#undef V_FENCE_PRE_ST_mo_seq
#undef V_LD
#undef V_LD_32
#undef V_LD_64
#undef V_LD_WFE
#undef V_LDLSE
#undef V_LDX
#undef V_LDX_32
#undef V_LDX_64
#undef V_MAP_await
#undef V_MAP_await_b_eq
#undef V_MAP_await_b_ge
#undef V_MAP_await_b_gt
#undef V_MAP_await_b_le
#undef V_MAP_await_b_lt
#undef V_MAP_await_b_neq
#undef V_MAP_await_b_not_eq
#undef V_MAP_await_b_not_ge
#undef V_MAP_await_b_not_gt
#undef V_MAP_await_b_not_le
#undef V_MAP_await_b_not_lt
#undef V_MAP_await_b_not_neq
#undef V_MAP_await_mo_acq
#undef V_MAP_await_mo_rel
#undef V_MAP_await_mo_rlx
#undef V_MAP_await_mo_seq
#undef V_MAP_await_op_add
#undef V_MAP_await_op_set
#undef V_MAP_await_op_sub
#undef V_MAP_COND
#undef V_MAP_COND_eq
#undef V_MAP_COND_ge
#undef V_MAP_COND_gt
#undef V_MAP_COND_le
#undef V_MAP_COND_lt
#undef V_MAP_COND_neq
#undef V_MAP_FAIL_MO
#undef V_MAP_FAIL_MO_mo_acq
#undef V_MAP_FAIL_MO_mo_rel
#undef V_MAP_FAIL_MO_mo_rlx
#undef V_MAP_FAIL_MO_mo_seq
#undef V_MAP_LD
#undef V_MAP_LD_mo_acq
#undef V_MAP_LD_mo_rel
#undef V_MAP_LD_mo_rlx
#undef V_MAP_LD_mo_seq
#undef V_MAP_max
#undef V_MAP_max_mo_acq
#undef V_MAP_max_mo_rel
#undef V_MAP_max_mo_rlx
#undef V_MAP_max_mo_seq
#undef V_MAP_MO
#undef V_MAP_MO_mo_acq
#undef V_MAP_MO_mo_rel
#undef V_MAP_MO_mo_rlx
#undef V_MAP_MO_mo_seq
#undef V_MAP_OP
#undef V_MAP_OP_add
#undef V_MAP_OP_set
#undef V_MAP_OP_sub
#undef V_MAP_R
#undef V_MAP_ST
#undef V_MAP_ST_mo_acq
#undef V_MAP_ST_mo_rel
#undef V_MAP_ST_mo_rlx
#undef V_MAP_ST_mo_seq
#undef V_MAX_CMP
#undef V_MOV
#undef V_MVN
#undef V_MVN_LDSE
#undef V_MVN_STLSE
#undef V_NEG
#undef V_NEG_LDLSE
#undef V_NEG_STLSE
#undef V_OP
#undef V_OP3
#undef V_OP_32
#undef V_OP_64
#undef V_OP_LD
#undef V_OP_LDLSE
#undef V_OP_LDLSE_mo_acq
#undef V_OP_LDLSE_mo_rel
#undef V_OP_LDLSE_mo_rlx
#undef V_OP_LDLSE_mo_seq
#undef V_OP_LD_mo_acq
#undef V_OP_LD_mo_rel
#undef V_OP_LD_mo_rlx
#undef V_OP_LD_mo_seq
#undef V_OP_LSE
#undef V_OP_LSE_mo_acq
#undef V_OP_LSE_mo_rel
#undef V_OP_LSE_mo_rlx
#undef V_OP_LSE_mo_seq
#undef V_OP_RMW
#undef V_OP_ST
#undef V_OP_STLSE
#undef V_OP_STLSE_mo_acq
#undef V_OP_STLSE_mo_rel
#undef V_OP_STLSE_mo_rlx
#undef V_OP_STLSE_mo_seq
#undef V_OP_ST_mo_acq
#undef V_OP_ST_mo_rel
#undef V_OP_ST_mo_rlx
#undef V_OP_ST_mo_seq
#undef V_PRFM
#undef V_R
#undef V_R2
#undef V_R3
#undef V_REMAP
#undef V_REMAP_mo_acq
#undef V_REMAP_mo_rel
#undef V_REMAP_mo_rlx
#undef V_REMAP_mo_seq
#undef V_SEVL
#undef V_ST
#undef V_ST_32
#undef V_ST_64
#undef V_STLSE
#undef V_STX
#undef V_STX_32
#undef V_STX_64
#undef V_SWP
#undef V_WFE
#undef V_WITH_LLSC_LXE
#undef V_WITH_LSE

#endif /* VATOMIC_UNDEF_H */
